Repository sous-chefs/docker, pull requests merged in 2021-09, with the labels that each got.

#1156 Fix private registries credentials handling and public registries
  CHANGELOG.md
  libraries/docker_base.rb
  libraries/docker_image.rb
Labels: Release: Patch

#1181 Fix container restart on every run when image has health checks
  CHANGELOG.md
  libraries/docker_container.rb
  spec/libraries/container_spec.rb
Labels: Release: Patch

#1182 Update test suites
  .github/workflows/ci.yml
  CHANGELOG.md
  kitchen.yml
Labels: Release: Minor

#1183 Docker Volume Custom Resource
  CHANGELOG.md
  libraries/docker_volume.rb
  metadata.rb
  resources/partial/_base.rb
  resources/volume.rb
Labels: Release: Major

#1184 Resource/container
  CHANGELOG.md
  libraries/docker_container.rb
  libraries/helpers_network.rb
  resources/container.rb
  spec/libraries/container_networks_spec.rb
  spec/libraries/container_spec.rb
  spec/spec_helper.rb
Labels: Release: Minor

#1185 Move the docker_exec resource to a library
  CHANGELOG.md
  libraries/docker_exec.rb
  resources/exec.rb
Labels: Release: Minor

#1188 Move the logging config to a partial so that it can be reused
  CHANGELOG.md
  resources/container.rb
  resources/partial/_base.rb
  resources/partial/_logging.rb
Labels: Release: Patch

#1075 Allow to specify the IP when connecting to a docker network
  CHANGELOG.md
  libraries/docker_network.rb
  test/cookbooks/docker_test/recipes/network.rb
  test/integration/network/inspec/assert_functioning_spec.rb
Labels: Release: Minor, Waiting on Contributor

#1191 Move the docker_network library to a custom resource
  CHANGELOG.md
  resources/network.rb
Labels: Release: Minor

#1190 Move the docker_plugin library to a custom resource
  CHANGELOG.md
  libraries/docker_plugin.rb
  resources/plugin.rb
  spec/docker_test/plugin_spec.rb
Labels: Release: Minor

#1193 update exec resource to use partial/_base
  CHANGELOG.md
  resources/exec.rb
Labels: Release: Patch

#1192 Move the docker_image library to a custom resource
  CHANGELOG.md
  libraries/docker_image.rb
  libraries/helpers_coerce.rb
  resources/image.rb
Labels: Release: Minor
