Repository sous-chefs/docker, pull requests merged in 2022-10, with the labels that each got.

#1217 Sort container volume_binds
  CHANGELOG.md
  resources/container.rb
Labels: Bug, Release: Patch, hacktoberfest-accepted

#1218 force-release
  README.md
Labels: Release: Patch

#1219 Fix arguments to generate_json in docker_image_prune resource
  CHANGELOG.md
  resources/image_prune.rb
Labels: Bug, Release: Patch
