Repository sous-chefs/docker, pull requests merged in 2024-07, with the labels that each got.

#1275 Version pin excon to v0.110.0
  CHANGELOG.md
  metadata.rb
Labels: Bug, Release: Patch

#1277 Bump changelog to trigger a new release
  CHANGELOG.md
Labels: Bug, Release: Patch

#1278 Bump docker-api gem dep to >= 2.3
  .github/workflows/ci.yml
  CHANGELOG.md
  kitchen.dokken.yml
  kitchen.global.yml
  kitchen.yml
  metadata.rb
  resources/installation_package.rb
  test/integration/install_and_stop/inspec/assert_functioning_spec.rb
  test/integration/installation_package/inspec/assert_functioning_spec.rb
Labels: Bug, Release: Patch

#1274 docker_installation_package: support for ubuntu 24.04
  .github/workflows/ci.yml
  CHANGELOG.md
  resources/installation_package.rb
Labels: Feature Request, Release: Minor

#1281 Use correct Debian Bookworm version
  CHANGELOG.md
  resources/installation_package.rb
Labels: Release: Patch
